export { default as Home } from './(main)/Home';
export { default as File } from './(main)/File';
export { default as Create } from './(main)/Create';
export { default as Tool } from './(main)/Tool';
export { default as Setting } from './(main)/Setting';
export { default as Splash } from './screens/Splash';
export { default as AllFiles } from './screens/AllFiles';
export { default as OcrCamera } from './screens/OcrCamera';
export { default as SignUp } from './auth/SignUp';
// export { default as DocumentPluginTest } from './screens/DocumentPluginTest';
// export { default as Scan } from './screens/Scan';
// export { default as ScannerTest } from './screens/ScannerTest';
